export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_TICKET_ERROR = 'CREATE_TICKET_ERROR';